### DISCUSSION TITLE
MY usecase...in svelte-kit, no less! Processing a group of iterated images...

### DISCUSSION THREAD

**Discussion by rchrdnsh** [JonasKruckenberg/imagetools#65] [Q&A]
Hi Jonas :-)

So, here is MY most pressing use case at the moment for image processing...not sure if this is possible to handle currently in image-tools, so please let me know :-)

I have a bunch of markdown files with frontmatter where an image path (or two, or three) is/are defined:

```yaml
---
order: 001
status: featured
category: words
title: Introduction
subtitle: Putting my brain on bits.
image: /words/introduction/circuit.jpg
alt: A blue computer circuit board.
---
```

Then in the svelte component I iterate through all the markdown files frontmatter, like so:

```html
<Container>
  <Grid>
    {#each articles as {slug, title, subtitle, image, status}}
      <Card
        path='words'
        slug={slug}
        title={title}
        subtitle={subtitle}
        image={image}
      />
    {/each}
  </Grid>
</Container>
```

...where the `image={image}` is what I want to process with image-tools.

Specifically, I want all the images that get looped over from all the markdown files to be processed the same way using image-tools.

so...is that currently possible using image-tools?
and if yes.........how?
and if no........would it be possible?

Thanks Jonas! XD
