### ISSUE TITLE
Usage inside CSS

### ISSUE THREAD

**Issue by hybridherbst** [JonasKruckenberg/imagetools#563]
When using vue, svelte, ... or other frameworks, often images are part of styles:
```css
<style>
.rice-drum {
    background-image: url(../components/static/Rice_Drum.jpg?format=webp);
}
</style>
```
vite resolves these properly, but it seems imagetools doesn't see them - they stay in the source format and are not transformed.

Is this expected?
